#!/usr/bin/env python3
"""mutate_selftest — prove `scripts/mutate.py` still discriminates, by making it fail.

Run it as `scripts/mutate.py --self-test`.

A harness whose only evidence is that it worked once is exactly the artifact issue #950 exists to
replace, so this exercises the FAILURE modes, not a happy path. It builds a throwaway cargo crate
in a temporary directory (never inside this repo, never part of the workspace) and drives the real
command-line entry point against it:

  1  anchor occurs ZERO times                  -> refuse, exit 2
  2  anchor occurs TWICE                       -> refuse, exit 2
  3  replacement identical to the anchor       -> refuse, exit 2 (a no-op mutant always scores
                                                  GREEN and would read as false evidence)
  4  mutant that does not compile              -> INVALID, never RED
  5  mutant that compiles and is caught        -> RED
  6  mutant that compiles and is not caught    -> GREEN
  7  multi-edit mutant: two edits that each SURVIVE alone but are CAUGHT together — the
     demonstration that a guarantee does not rest on an unrelated accident
  8  the harness's own compile-sentinel gate, WRAPPED away  -> loud crash, still not a RED
  9  that gate, the type assertion behind it, and the report's use of the proof object, all
     three wrapped away -> only now does a mutant that never compiled get printed as RED. The
     counterfactual proving those guards are reached and load-bearing rather than merely
     present in the file (#799)
 10  the harness's restore write, corrupted    -> the sha256 verification fires, loudly, and the
     file really is left different (so the alarm is true, not spurious)

Cases 8-10 mutate a COPY of `scripts/mutate.py` using the harness's own edit engine. Nothing in
this file writes to a tracked path.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

from mutate import Refusal, apply_edit, sha256_bytes

HARNESS = Path(__file__).resolve().parent / "mutate.py"

# --------------------------------------------------------------------------------------------
# The throwaway subject crate.
# --------------------------------------------------------------------------------------------

SUBJECT_CARGO_TOML = """\
# Generated by scripts/mutate.py --self-test into a temporary directory. Not part of any
# eqoxide workspace; the empty [workspace] table keeps it self-contained wherever TMPDIR points.
[workspace]

[package]
name = "mutate_selftest_subject"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"
"""

SUBJECT_LIB_RS = """\
//! Subject crate for `scripts/mutate.py --self-test`. Generated at run time into a temporary
//! directory; never committed, never part of the eqoxide workspace.

/// Covered by `classify_is_reached`. A mutant here must be caught.
pub fn classify(x: i32) -> &'static str {
    if x > 10 {
        "big"
    } else {
        "small"
    }
}

/// Deliberately covered by NO test. A mutant here must survive.
pub fn label(x: i32) -> &'static str {
    if x > 10 {
        "over"
    } else {
        "under"
    }
}

/// The primary source of the answer.
pub fn primary() -> i32 {
    7
}

/// The fallback. It happens to agree with `primary`, which is the accident that lets a
/// single-edit mutant on either function survive.
pub fn fallback() -> i32 {
    7
}

pub fn resolve() -> i32 {
    if primary() == 7 {
        primary()
    } else {
        fallback()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_is_reached() {
        assert_eq!(classify(11), "big");
        assert_eq!(classify(3), "small");
    }

    #[test]
    fn resolve_is_seven() {
        assert_eq!(resolve(), 7);
    }
}
"""

CLASSIFY_ANCHOR = """\
pub fn classify(x: i32) -> &'static str {
    if x > 10 {
        "big"
    } else {
        "small"
    }
}
"""

RUN_BLOCK = """\
name = "mutate.py self-test"

[run]
command = ["cargo", "test", "--all-targets"]
timeout_secs = 600
"""


def spec_anchor_zero() -> str:
    return (
        RUN_BLOCK
        + """
[[mutant]]
id = "anchor-absent"
description = "the anchor text is not in the file at all"
expect = "RED"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''
    if x > 99999 {
'''
  replacement = '''
    if false {
'''
"""
    )


def spec_anchor_twice() -> str:
    return (
        RUN_BLOCK
        + """
[[mutant]]
id = "anchor-ambiguous"
description = "the anchor matches both classify() and label()"
expect = "RED"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''
    if x > 10 {
'''
  replacement = '''
    if false {
'''
"""
    )


def spec_noop() -> str:
    return (
        RUN_BLOCK
        + """
[[mutant]]
id = "no-op"
description = "replacement is byte-identical to the anchor, so nothing is perturbed"
expect = "GREEN"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''
    if x > 10 {
        "over"
'''
  replacement = '''
    if x > 10 {
        "over"
'''
"""
    )


def spec_invalid() -> str:
    return (
        RUN_BLOCK
        + """
[[mutant]]
id = "does-not-compile"
description = "WRAP whose else-arm returns i32 where &str is required — a type error"
expect = "INVALID"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''
"""
        + CLASSIFY_ANCHOR
        + """'''
  replacement = '''
pub fn classify(x: i32) -> &'static str {
    if false {
        if x > 10 { "big" } else { "small" }
    } else {
        x
    }
}
'''
"""
    )


def spec_red() -> str:
    return (
        RUN_BLOCK
        + """
[[mutant]]
id = "caught"
description = "WRAP classify() to always answer \\"small\\"; classify_is_reached must fail"
expect = "RED"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''
"""
        + CLASSIFY_ANCHOR
        + """'''
  replacement = '''
pub fn classify(x: i32) -> &'static str {
    if false {
        if x > 10 { "big" } else { "small" }
    } else {
        "small"
    }
}
'''
"""
    )


def spec_green() -> str:
    return (
        RUN_BLOCK
        + """
[[mutant]]
id = "survives"
description = "WRAP label(), which no test exercises"
expect = "GREEN"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''
pub fn label(x: i32) -> &'static str {
    if x > 10 {
        "over"
    } else {
        "under"
    }
}
'''
  replacement = '''
pub fn label(x: i32) -> &'static str {
    if false {
        if x > 10 { "over" } else { "under" }
    } else {
        "neither"
    }
}
'''
"""
    )


def spec_multi() -> str:
    primary_anchor = """
pub fn primary() -> i32 {
    7
}
"""
    primary_wrap = """
pub fn primary() -> i32 {
    if false { 7 } else { 9 }
}
"""
    fallback_anchor = """
pub fn fallback() -> i32 {
    7
}
"""
    fallback_wrap = """
pub fn fallback() -> i32 {
    if false { 7 } else { 9 }
}
"""
    return (
        RUN_BLOCK
        + f"""
[[mutant]]
id = "primary-alone"
description = "WRAP primary() only — resolve() falls through to fallback(), which agrees, so the test still passes"
expect = "GREEN"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''{primary_anchor}'''
  replacement = '''{primary_wrap}'''

[[mutant]]
id = "fallback-alone"
description = "WRAP fallback() only — never reached while primary() answers 7"
expect = "GREEN"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''{fallback_anchor}'''
  replacement = '''{fallback_wrap}'''

[[mutant]]
id = "both"
description = "WRAP the check AND the path it falls back to — only the pair is caught, which is what shows resolve_is_seven rests on the two agreeing rather than on either one"
expect = "RED"

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''{primary_anchor}'''
  replacement = '''{primary_wrap}'''

  [[mutant.edit]]
  file = "src/lib.rs"
  anchor = '''{fallback_anchor}'''
  replacement = '''{fallback_wrap}'''
"""
    )


# --------------------------------------------------------------------------------------------
# Mutants of the harness itself.
# --------------------------------------------------------------------------------------------

GATE_ANCHOR = """\
    proof = find_compile_proof(output)
    if proof is None:
        return INVALID, "no compile sentinel in the log — the mutant did not build, nothing was tested"
"""

GATE_WRAP = """\
    proof = find_compile_proof(output)
    if False:
        if proof is None:
            return INVALID, "no compile sentinel in the log — the mutant did not build, nothing was tested"
"""

TYPE_GUARD_ANCHOR = '        raise AssertionError("verdict_from_proof called without a CompileProof")\n'
TYPE_GUARD_WRAP = "        pass  # self-test: type guard wrapped away\n"

EVIDENCE_ANCHOR = "    return verdict_from_proof(proof, returncode), proof.line.strip()\n"

EVIDENCE_WRAP = """\
    if False:
        return verdict_from_proof(proof, returncode), proof.line.strip()
    else:
        return verdict_from_proof(proof, returncode), "self-test: evidence fabricated"
"""

RESTORE_ANCHOR = """\
    def restore_and_verify(self) -> None:
        self.path.write_bytes(self.original)
"""

RESTORE_WRAP = (
    "    def restore_and_verify(self) -> None:\n"
    "        if False:\n"
    "            self.path.write_bytes(self.original)\n"
    "        else:\n"
    '            self.path.write_bytes(self.original + b"// self-test corruption\\n")\n'
)


def mutated_harness(dest: Path, edits: list[tuple[str, str]]) -> Path:
    """Write a mutated copy of the harness, using the harness's own edit engine."""
    text = HARNESS.read_text(encoding="utf-8")
    for i, (anchor, replacement) in enumerate(edits):
        text = apply_edit(text, anchor, replacement, f"harness self-mutant edit #{i + 1}")
    dest.write_text(text, encoding="utf-8")
    return dest


# --------------------------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------------------------


class Checker:
    def __init__(self) -> None:
        self.failures: list[str] = []

    def check(self, label: str, ok: bool, detail: str = "") -> None:
        mark = "PASS" if ok else "FAIL"
        print(f"    [{mark}] {label}" + (f" — {detail}" if detail else ""))
        if not ok:
            self.failures.append(label)


def write_subject(root: Path) -> Path:
    (root / "src").mkdir(parents=True, exist_ok=True)
    (root / "Cargo.toml").write_text(SUBJECT_CARGO_TOML, encoding="utf-8")
    lib = root / "src" / "lib.rs"
    lib.write_text(SUBJECT_LIB_RS, encoding="utf-8")
    return lib


def run_harness(harness: Path, spec: Path, root: Path, logs: Path) -> tuple[int, str, str]:
    completed = subprocess.run(
        [sys.executable, str(harness), str(spec), "--root", str(root), "--logs", str(logs)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return (
        completed.returncode,
        completed.stdout.decode("utf-8", "replace"),
        completed.stderr.decode("utf-8", "replace"),
    )


def tail(text: str, lines: int) -> str:
    return "\n".join(text.rstrip().splitlines()[-lines:])


def verdict_row(stdout: str, mutant_id: str) -> str:
    """The verdict cell for one mutant, read back out of the printed markdown table."""
    for line in stdout.splitlines():
        if line.startswith(f"| `{mutant_id}` |"):
            return line.split("|")[3].strip()
    return "<no row>"


def self_test() -> int:
    workdir = Path(tempfile.mkdtemp(prefix="mutate-selftest-"))
    subject = workdir / "subject"
    lib = write_subject(subject)
    pristine = lib.read_bytes()
    pristine_sha = sha256_bytes(pristine)
    specs = workdir / "specs"
    specs.mkdir()
    logs = workdir / "logs"
    logs.mkdir()

    print("mutate.py --self-test")
    print(f"  harness  : {HARNESS}")
    print(f"  workdir  : {workdir}")
    print(f"  subject  : src/lib.rs sha256 {pristine_sha}")
    print()

    c = Checker()

    def spec_file(name: str, body: str) -> Path:
        path = specs / f"{name}.toml"
        path.write_text(body, encoding="utf-8")
        return path

    # ---- refusals: these must never reach cargo at all -------------------------------------
    for case, body, needle in (
        ("1  anchor occurs ZERO times", spec_anchor_zero(), "anchor occurs 0 time(s)"),
        ("2  anchor occurs TWICE", spec_anchor_twice(), "anchor occurs 2 time(s)"),
        ("3  no-op mutant", spec_noop(), "identical to the anchor"),
    ):
        name = case.split()[0]
        print(f"CASE {case}")
        code, out, err = run_harness(HARNESS, spec_file(f"case{name}", body), subject, logs)
        c.check(f"case {name}: exit 2 (refusal)", code == 2, f"got {code}")
        reason = next((ln for ln in err.splitlines() if needle in ln), "<needle not in stderr>")
        c.check(f"case {name}: says why", needle in err, reason.strip())
        c.check(f"case {name}: no verdict was printed", "| RED |" not in out and "| GREEN |" not in out)
        c.check(f"case {name}: file untouched", sha256_bytes(lib.read_bytes()) == pristine_sha)
        print()

    # ---- scored mutants --------------------------------------------------------------------
    for case, body, ids in (
        ("4  non-compiling mutant", spec_invalid(), {"does-not-compile": "INVALID"}),
        ("5  compiles and is caught", spec_red(), {"caught": "RED"}),
        ("6  compiles and is not caught", spec_green(), {"survives": "GREEN"}),
        (
            "7  multi-edit mutant",
            spec_multi(),
            {"primary-alone": "GREEN", "fallback-alone": "GREEN", "both": "RED"},
        ),
    ):
        name = case.split()[0]
        print(f"CASE {case}")
        code, out, err = run_harness(HARNESS, spec_file(f"case{name}", body), subject, logs)
        print(out.rstrip())
        c.check(f"case {name}: exit 0 (all expectations met)", code == 0, f"got {code}\n{err}")
        for mutant_id, want in ids.items():
            got = verdict_row(out, mutant_id)
            c.check(f"case {name}: {mutant_id} scored {want}", got == want, f"got {got}")
        if name == "4":
            c.check("case 4: no row of the table says RED", "| RED |" not in out)
        c.check(f"case {name}: file restored", sha256_bytes(lib.read_bytes()) == pristine_sha)
        print()

    invalid_spec = specs / "case4.toml"
    red_spec = specs / "case5.toml"

    # ---- 8: wrap the compile-sentinel gate away -------------------------------------------
    print("CASE 8  harness self-mutant: the compile-sentinel gate WRAPPED away")
    h8 = mutated_harness(workdir / "mutate_gate_wrapped.py", [(GATE_ANCHOR, GATE_WRAP)])
    code, out, err = run_harness(h8, invalid_spec, subject, logs)
    print(tail(out + err, 8))
    c.check("case 8: does not exit 0", code != 0, f"got {code}")
    c.check("case 8: never reports a verdict", "| RED |" not in out and "| GREEN |" not in out)
    c.check(
        "case 8: fails on the type guard behind the gate",
        "verdict_from_proof called without a CompileProof" in err,
    )
    c.check("case 8: file restored", sha256_bytes(lib.read_bytes()) == pristine_sha)
    print()

    # ---- 9: wrap away ALL THREE things that stand between a missing sentinel and a RED ------
    print("CASE 9  harness self-mutant: all three guards wrapped away (3-edit)")
    h9 = mutated_harness(
        workdir / "mutate_all_guards_wrapped.py",
        [
            (GATE_ANCHOR, GATE_WRAP),
            (TYPE_GUARD_ANCHOR, TYPE_GUARD_WRAP),
            (EVIDENCE_ANCHOR, EVIDENCE_WRAP),
        ],
    )
    code, out, err = run_harness(h9, invalid_spec, subject, logs)
    print(out.rstrip())
    got = verdict_row(out, "does-not-compile")
    c.check(
        "case 9: with all three gone, a mutant that never compiled IS reported RED",
        got == "RED",
        f"got {got}",
    )
    c.check("case 9: and the spec's expect=INVALID catches it as a mismatch", code == 1, f"got {code}")
    c.check("case 9: file restored", sha256_bytes(lib.read_bytes()) == pristine_sha)
    print("    (cases 8+9 are the reach proof. The sentinel gate, the type assertion in")
    print("     verdict_from_proof, and the report's use of the proof object must ALL be removed")
    print("     before a mutant that never compiled can be printed as RED; wrapping the gate")
    print("     alone changes INVALID into a loud crash, never into a verdict.)")
    print()

    # ---- 10: corrupt the restore ------------------------------------------------------------
    print("CASE 10  harness self-mutant: the restore write corrupted")
    h10 = mutated_harness(workdir / "mutate_restore_corrupted.py", [(RESTORE_ANCHOR, RESTORE_WRAP)])
    code, out, err = run_harness(h10, red_spec, subject, logs)
    print(tail(out + err, 6))
    c.check("case 10: exit 2 (refusal)", code == 2, f"got {code}")
    c.check("case 10: the sha256 verification fires", "RESTORE VERIFICATION FAILED" in err)
    c.check("case 10: no verdict is reported for the aborted run", "| RED |" not in out)
    c.check(
        "case 10: and the alarm is TRUE — the file really is left different",
        sha256_bytes(lib.read_bytes()) != pristine_sha,
    )
    lib.write_bytes(pristine)  # our own cleanup; the corrupted copy is in a temporary directory
    print()

    print("=" * 90)
    if c.failures:
        print(f"SELF-TEST FAILED — {len(c.failures)} check(s) did not hold:")
        for failure in c.failures:
            print(f"  - {failure}")
        print(f"workdir kept for inspection: {workdir}")
        return 1
    print("SELF-TEST PASSED — every failure mode above was demonstrated, not assumed.")
    print(f"workdir: {workdir}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(self_test())
    except Refusal as exc:
        print(f"self-test REFUSED: {exc}", file=sys.stderr)
        sys.exit(2)
