//! Full-client entry point.
//!
//! Loads config + the EQ string table, creates the shared request slots (`Arc<Mutex<…>>`) and the
//! mpsc packet channel, then starts the three concurrent halves: the EQ network thread
//! (`run_login_flow`, skipped with `--testzone`), the HTTP API server, and the winit/wgpu render
//! loop on the main thread. The request slots are the cross-thread glue — HTTP writes them, the nav
//! thread drains them. `--testzone` runs the renderer offline (no server) for asset/zone debugging.

use eq_renderer::{assets, camera_state, config, eq_net, eqstr, http};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::sync::atomic::{AtomicBool, Ordering};
use winit::event_loop::EventLoop;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let testzone_mode = args.contains(&"--testzone".to_string());

    // `--config <path>` selects the per-character login config; defaults to the eq-client-ref config.
    let login_cfg_path = args
        .iter()
        .position(|a| a == "--config")
        .and_then(|i| args.get(i + 1))
        .map(|p| std::path::PathBuf::from(shellexpand::tilde(p).into_owned()))
        .unwrap_or_else(|| {
            std::path::PathBuf::from(shellexpand::tilde("~/git/eq-client-ref/config.yaml").into_owned())
        });
    eprintln!("renderer: loading login config from {}", login_cfg_path.display());

    let login_cfg = config::LoginConfig::load(&login_cfg_path);
    let app_cfg   = config::AppConfig::load();

    // Load the EQ string table for OP_FormattedMessage / OP_SimpleMessage rendering.
    eqstr::load(&app_cfg.assets_path.join("eqstr_us.txt"));

    // Load quest-giver data (generated by tools/quest_finder.py --export) for the golden "!"
    // indicators and the GET /quests endpoint. Missing file = no indicators (client still runs).
    eq_renderer::quests::load(std::path::Path::new("data/quests.json"));

    let camera_cmd: Arc<Mutex<Option<camera_state::CameraCmd>>> = Arc::new(Mutex::new(None));
    let camera_snapshot: Arc<Mutex<camera_state::CameraSnapshot>> = Arc::new(Mutex::new(
        camera_state::CameraState::new([0.0, 0.0, 0.0], 0.0).snapshot(),
    ));

    let (app_tx, app_rx) = tokio::sync::mpsc::unbounded_channel::<eq_net::AppPacket>();

    // Shared clean-shutdown flag. Set by POST /exit and by window-close; observed by the
    // EQ network thread, which performs the logout sequence and exits the process.
    let shutdown: Arc<AtomicBool> = Arc::new(AtomicBool::new(false));

    // Route SIGTERM/SIGINT into the same clean-shutdown flag so a killed process (e.g.
    // `timeout N ./eq_renderer`, Ctrl-C, or `kill <pid>`) logs out cleanly instead of dropping
    // its UDP stream. A sudden drop leaves the character LINKDEAD on the server for
    // Zone:ClientLinkdeadMS (90s) before it can be re-logged; a clean OP_Logout removes it
    // immediately. signal-hook's handler only stores into the AtomicBool (async-signal-safe);
    // the network thread observes the flag and runs the OP_Logout sequence.
    for sig in [signal_hook::consts::SIGTERM, signal_hook::consts::SIGINT] {
        if let Err(e) = signal_hook::flag::register(sig, Arc::clone(&shutdown)) {
            eprintln!("warning: failed to register signal {sig} for clean shutdown: {e}");
        }
    }

    let goto_target:      http::GotoTarget      = Arc::new(Mutex::new(None));
    let entity_positions: http::EntityPositions = Arc::new(Mutex::new(HashMap::new()));
    let entity_ids:       http::EntityIds       = Arc::new(Mutex::new(HashMap::new()));
    let zone_points:      http::ZonePoints      = Arc::new(Mutex::new(Vec::new()));
    let task_log:         http::TaskLog         = Arc::new(Mutex::new(Vec::new()));
    let zone_cross:       http::ZoneCrossReq    = Arc::new(Mutex::new(None));
    let warp:             http::WarpReq         = Arc::new(Mutex::new(None));
    let hail:             http::HailReq         = Arc::new(Mutex::new(None));
    let say:              http::SayReq          = Arc::new(Mutex::new(None));
    let target:           http::TargetReq       = Arc::new(Mutex::new(None));
    let attack:           http::AttackReq       = Arc::new(Mutex::new(None));
    let buy:              http::BuyReq          = Arc::new(Mutex::new(None));
    let move_req:         http::MoveReq         = Arc::new(Mutex::new(None));
    let give:             http::GiveReq         = Arc::new(Mutex::new(None));
    let inventory:        http::InventoryShared = Arc::new(Mutex::new(Vec::new()));
    let loot:             http::LootReq         = Arc::new(Mutex::new(None));
    let door_click:       http::DoorClickReq    = Arc::new(Mutex::new(None));
    let doors_shared:     http::DoorsShared     = Arc::new(Mutex::new(Vec::new()));
    let messages:         http::MessagesShared  = Arc::new(Mutex::new(Vec::new()));
    let cast:             http::CastReq         = Arc::new(Mutex::new(None));
    let sit:              http::SitReq          = Arc::new(Mutex::new(None));
    let consider:         http::ConsiderReq     = Arc::new(Mutex::new(None));
    let spells_path = std::env::var("EQ_SPELLS_FILE")
        .unwrap_or_else(|_| "~/git/original-client/spells_us.txt".to_string());
    let spells: std::sync::Arc<eq_renderer::spells::SpellDb> =
        std::sync::Arc::new(eq_renderer::spells::SpellDb::load(&spells_path));
    let shared_collision: assets::SharedCollision = Arc::new(std::sync::RwLock::new(None));
    let frame_req:        http::FrameReq        = Arc::new(Mutex::new(None));
    let player_info:      http::PlayerInfo      = Arc::new(Mutex::new(http::PlayerState::default()));

    // EQ network task — skipped in --testzone mode (offline debug)
    let character_name = login_cfg.character_name.clone();
    let asset_user     = login_cfg.username.clone();
    let asset_pass     = login_cfg.password.clone();
    let asset_server_url = app_cfg.asset_server_url.clone();
    if !testzone_mode {
        let gt  = goto_target.clone();
        let ep  = entity_positions.clone();
        let ei  = entity_ids.clone();
        let zp  = zone_points.clone();
        let tl  = task_log.clone();
        let zc  = zone_cross.clone();
        let hl  = hail.clone();
        let sy  = say.clone();
        let tg  = target.clone();
        let at  = attack.clone();
        let by  = buy.clone();
        let mv  = move_req.clone();
        let gv  = give.clone();
        let iv  = inventory.clone();
        let lt  = loot.clone();
        let dc  = door_click.clone();
        let ds  = doors_shared.clone();
        let mg  = messages.clone();
        let ca  = cast.clone();
        let st  = sit.clone();
        let co  = consider.clone();
        let sc  = shared_collision.clone();
        let sd  = shutdown.clone();
        let md  = app_cfg.assets_path.join("maps");
        std::thread::spawn(move || {
            let rt = tokio::runtime::Runtime::new().expect("tokio runtime");
            rt.block_on(async {
                if let Err(e) = eq_net::run_login_flow(login_cfg, app_tx, 10, gt, ep, ei, zp, tl, zc, hl, sy, tg, at, by, mv, gv, iv, lt, dc, ds, mg, ca, st, co, sc, md, sd).await {
                    eprintln!("EQ: fatal: {e}");
                }
            });
        });
    }

    // HTTP server
    let app_goto = goto_target.clone();
    let app_hail   = hail.clone();
    let app_say    = say.clone();
    let app_target = target.clone();
    let app_attack  = attack.clone();
    let app_cast    = cast.clone();
    let app_sit     = sit.clone();
    let app_consider = consider.clone();
    let app_spells  = spells.clone();
    let app_door_click = door_click.clone();
    let app_player_info = player_info.clone();
    http::spawn_camera_server(
        camera_cmd.clone(),
        camera_snapshot.clone(),
        frame_req.clone(),
        goto_target,
        entity_positions,
        entity_ids,
        zone_points,
        zone_cross,
        warp.clone(),
        hail,
        say,
        target,
        attack,
        cast.clone(),
        sit.clone(),
        consider.clone(),
        buy,
        move_req,
        give,
        inventory,
        loot,
        messages,
        spells.clone(),
        player_info,
        task_log,
        door_click,
        doors_shared,
        shutdown.clone(),
        app_cfg.http_port,
    );

    let event_loop = EventLoop::new().expect("event loop");
    let mut application = eq_renderer::app::App::new(
        app_cfg.assets_path,
        app_cfg.models_path,
        character_name,
        camera_cmd,
        camera_snapshot,
        app_rx,
        frame_req,
        app_goto,
        app_hail,
        app_say,
        app_target,
        app_attack,
        app_cast,
        app_sit,
        app_consider,
        app_spells,
        app_door_click,
        shared_collision,
        app_player_info,
        warp,
        testzone_mode,
        shutdown.clone(),
        asset_server_url,
        asset_user,
        asset_pass,
    );
    event_loop.run_app(&mut application).expect("event loop run");
    // The event loop has now exited gracefully — either the window was closed, or a shutdown was
    // requested (POST /exit / OP_GMKick set the flag and `about_to_wait` called `event_loop.exit()`).
    // Either way winit has torn down its Wayland clipboard worker on this (main) thread, so it is now
    // safe to exit the process. Ensure the flag is set so the EQ network thread logs the character
    // out (it idles after sending OP_Logout + OP_SessionDisconnect), give it a moment, then exit.
    shutdown.store(true, Ordering::Relaxed);
    std::thread::sleep(std::time::Duration::from_millis(1500));
    std::process::exit(0);
}
